services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: client/.env.local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: sh -c "yarn install && yarn build && yarn start"
    networks:
      - my-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: server/.env
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
