services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: sh -c "yarn install && yarn build && yarn start"
    networks:
      - my-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
    - FLASK_APP=app.py
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
